spring.application.name=spring-security-workshop-june

#MYSQL Configuration

#spring.datasource.url=jdbc:mysql://localhost:3308/securityworkspace
#spring.datasource.username=TP000036109
#spring.datasource.password=Mumbai#202603
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#H2 Database Configuration

spring.h2.console.enabled=true

spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=sa

 
#Security Properties
security.jwt.secret-key=iamlearningjwtsecurityfromtechamplifiersforclearinnginterviews
security.jwt.expiration-time=360000